[project]
name = 'stacksminimint'
description = 'A minimal NFT minting platform on Stacks'
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.sip-009-nft-trait-v2-2]
path = 'contracts/archive/sip-009-nft-trait-v2-2.clar'
clarity_version = 2
epoch = 2.4

[contracts.sip-010-trait-ft-standard-v2-2]
path = 'contracts/archive/sip-010-trait-ft-standard-v2-2.clar'
clarity_version = 2
epoch = 2.4

[contracts.minimint-core-v2]
path = 'contracts/minimint-core-v2.clar'
clarity_version = 2
epoch = 2.4

[contracts.minimint-token-v2]
path = 'contracts/minimint-token-v2.clar'
clarity_version = 2
epoch = 2.4

[contracts.minimint-hub-v2]
path = 'contracts/minimint-hub-v2.clar'
clarity_version = 2
epoch = 2.4
depends_on = ["minimint-core-v2", "minimint-token-v2"]

[repl.analysis]
passes = ['call_checker', 'check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
api_url = 'https://api.hiro.so'
