[project]
name = 'stacksminimint'
description = 'A minimal NFT minting platform on Stacks'
authors = []
telemetry = false
cache_dir = './.cache'
requirements = [
  { contract_id = "SP2PABVDXFNZ651AM11M9FE58F5KCXCE80FA019P1.nft-trait" },
  { contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard" }
]

[contracts.minimint-core]
path = 'contracts/minimint-core.clar'
clarity_version = 2
epoch = 2.4

[contracts.minimint-token]
path = 'contracts/minimint-token.clar'
clarity_version = 2
epoch = 2.4

[contracts.minimint-hub]
path = 'contracts/minimint-hub.clar'
clarity_version = 2
epoch = 2.4
depends_on = ["minimint-core", "minimint-token"]

[repl.analysis]
passes = ['call_checker', 'check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
api_url = 'https://api.hiro.so'
