[network]
name = "mainnet"
stacks_node_rpc_address = "https://api.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
# It is strongly suggested to use encrypted mnemonics to avoid putting
# seed phrases directly into TOML files.  To do so, run:
#
#     clarinet deployments encrypt
#
# Enter your seed phrase and a password, then paste the encrypted mnemonic here.
#
# Otherwise, use the mnemonic field below:
mnemonic = "usage upon hawk topic waste mobile stairs daughter hobby weekend answer illness"

# ================================
# Deployment Plan Override
# ================================
# Deploy exactly 3 contracts with exactly 0.02 STX fee per transaction

[[plan.transactions]]
contract-publish = { contract-name = "minimint-core", expected-sender = "SP5K2RHMSBH4PAP4PGX77MCVNK1ZEED07CWX9TJT", fee = 20000, cost = 100000000 }

[[plan.transactions]]
contract-publish = { contract-name = "minimint-token", expected-sender = "SP5K2RHMSBH4PAP4PGX77MCVNK1ZEED07CWX9TJT", fee = 20000, cost = 100000000 }

[[plan.transactions]]
contract-publish = { contract-name = "minimint-hub", expected-sender = "SP5K2RHMSBH4PAP4PGX77MCVNK1ZEED07CWX9TJT", fee = 20000, cost = 100000000 }
