import {
  CONTRACT_ADDRESS as SDK_CONTRACT_ADDRESS,
  CONTRACT_NAME as SDK_CONTRACT_NAME,
  DEFAULT_NETWORK,
  FUNCTIONS as SDK_FUNCTIONS,
  MINT_FEE as SDK_MINT_FEE,
  STACKS_NETWORK_CONFIG as SDK_STACKS_NETWORK_CONFIG,
} from 'stacksminimint-sdk';

export const CONTRACT_ADDRESS = SDK_CONTRACT_ADDRESS;
export const CONTRACT_NAME = SDK_CONTRACT_NAME;
export const NETWORK = DEFAULT_NETWORK; // 'mainnet' or 'testnet'
export const MINT_FEE = SDK_MINT_FEE; // 0.001 STX (in micro-STX)

export const FUNCTIONS = SDK_FUNCTIONS;
export const STACKS_NETWORK_CONFIG = SDK_STACKS_NETWORK_CONFIG;
export const MAX_SUPPLY = 10000;
